name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install C++/C compilers on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgsl-dev

      - name: Install C++/C compilers on macOS
        if: startsWith(matrix.os, 'macos-')
        run: brew install gsl

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.1

      - name: Build wheels
        env:
            CIBW_BEFORE_BUILD: pip install six diffpy.structure cython cmake
            CIBW_BUILD: "cp310-* cp311-* cp312-*"
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
  # make_sdist:
  #   name: Make SDist
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0  # Optional, use if you use setuptools_scm
  #       submodules: true  # Optional, use if you have submodules    

  #   - name: Build SDist
  #     run: pipx run build --sdist    

  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: cibw-sdist
  #       path: dist/*.tar.gz